{% set name = "LHAPDF" %}
{% set version = "6.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://lhapdf.hepforge.org/downloads/?f=LHAPDF-{{ version }}.tar.gz
  sha256: 2443a4b32cc3b0597c8248bd6e25703ace9c91a7a253c5f60b1b5428ef9c869e
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

about:
  home: https://lhapdf.hepforge.org/
  license: GPL-2.0-or-later
  summary: "LHAPDF is a general-purpose C++ interpolation library, used for evaluating PDFs in high-energy physics."
  description: |
    LHAPDF (Les Houches Accord PDF) is a library for parton density functions (PDFs), widely used in high-energy physics.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Kwaizer